{% set name = "tcolorpy" %}
{% set version = "0.1.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f0dceb1cb95e554cee63024b3cd2fd8d4628c568773de2d1e6b4f0478461901c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
    - releasecmd
  run:
    - python >=3.5

test:
  imports:
    - tcolorpy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/thombashi/tcolorpy
  summary: tcolopy is a Python library to apply true color for terminal text.
  dev_url: https://github.com/thombashi/tcolorpy
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - basnijholt
